# Generated by Django 3.0.7 on 2020-07-14 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('yr', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Student')),
            ],
        ),
    ]
