# Generated by Django 3.0.7 on 2020-07-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pseller',
            field=models.CharField(choices=[('Flipkart', 'Flipkart'), ('Amazon', 'Amazon'), ('Myntra', 'Myntra'), ('Snapdeal', 'Snapdeal')], max_length=30),
        ),
    ]
